### PR TITLE
Adjust alchemy page to new interface

### PR DESCRIPTION
**Pull request by wdspkr**
As Alchemy 3.4 introduced a new publication interface we need to adjust to it.

### CODE REVIEW

**Comment by tvdeyen** [comment]
In order to fix the tests, you need to update the dummy app to the latest Alchemy master.

**Comment by tvdeyen** [comment]
For this you need to go into `spec/dummy` and
1. `bin/rake rails:update`
2. `bin/rake alchemy:upgrade`

and follow instructions

**Comment by wdspkr** [comment]
I cherry-picked the commit from https://github.com/AlchemyCMS/alchemy-pg_search/pull/6.

**Comment by wdspkr** [comment]
...and updated the dummy app.

**Comment by tvdeyen** [comment]
This is great. Thank you!

**Pull request merged**
